version: "3.7"
services:
  app:
    build:
      args:
        user: ${UNIX_USER}
        uid: ${UNIX_UID}
      context: ./
      dockerfile: Dockerfile
    image: ${PROJECT}
    container_name: ${PROJECT}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ${PROJECT}-network

  db:
    image: mariadb
    container_name: ${PROJECT}_mysql
    restart: unless-stopped
    tty: true
    build:
      context: .
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - ${PROJECT}-network

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - ${PROJECT}-network

networks:
  test-network:
    driver: bridge
